### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rvion** [lukexi/stack-ide-sublime#5]
Just set up `stack` and `stack ide` on new machine, then `stack new --resolver nightly-2015-06-28`, then cloned `stack-ide-sublime` in right folder of ST3, then started sublime, and got:

```
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x1122fb390>> ignored
Switched syntax to SublimeHaskell's fixed Haskell syntax: /Users/rvion/yesodtest/app/Main.hs
```

in terminal, `stack ide` yields:

```
{"tag":"ResponseWelcome","contents":[0,1,0]}
{"tag":"ResponseLog","contents":"[Info] Initializing ide-backend session @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:195:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Session dir = /Users/rvion/yesodtest/session.74541 @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:208:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Dist dir = /Users/rvion/yesodtest/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/ @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:210:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Local working dir = /Users/rvion/yesodtest/ @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:217:17)\n"}
{"tag":"ResponseLog","contents":"[Info] Searching for ide-backend-server on this path: /Users/rvion/yesodtest/.stack-work/install/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.stack/snapshots/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.local/bin/:/Users/rvion/.nix-profile/bin:/Users/rvion/.nix-profile/sbin:/Users/rvion/dev/go/bin:/Users/rvion/dev/Nim/bin/:/Users/rvion/.babel/pkgs/babel-0.4.0:/Users/rvion/.babel/bin/:/Users/rvion/Library/Haskell/bin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:341:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Found ide-backend-server - using this one: /Users/rvion/.local/bin/ide-backend-server @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:343:5)\n"}
{"tag":"ResponseLog","contents":"[Debug] Recompile required, starting... @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update.ExecuteSessionUpdate ./IdeSession/Update/ExecuteSessionUpdate.hs:225:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Restarting session due to update requiring it. @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:422:11)\n"}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusRequiredRestart","contents":[]}}
{"tag":"ResponseLog","contents":"[Info] Restarting ide-backend-server @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:351:3)\n"}
{"tag":"ResponseLog","contents":"[Info] Searching for ide-backend-server on this path: /Users/rvion/yesodtest/.stack-work/install/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.stack/snapshots/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.local/bin/:/Users/rvion/.nix-profile/bin:/Users/rvion/.nix-profile/sbin:/Users/rvion/dev/go/bin:/Users/rvion/dev/Nim/bin/:/Users/rvion/.babel/pkgs/babel-0.4.0:/Users/rvion/.babel/bin/:/Users/rvion/Library/Haskell/bin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:341:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Found ide-backend-server - using this one: /Users/rvion/.local/bin/ide-backend-server @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:343:5)\n"}
{"tag":"ResponseLog","contents":"[Debug] Recompile required, starting... @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update.ExecuteSessionUpdate ./IdeSession/Update/ExecuteSessionUpdate.hs:225:5)\n"}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusProgress","contents":{"progressOrigMsg":"[1 of 1] Compiling Lib              ( /Users/rvion/yesodtest/src/Lib.hs, interpreted )","progressStep":1,"progressNumSteps":1,"progressParsedMsg":"Compiling Lib"}}}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusDone","contents":[]}}
```

**Comment by rvion** [comment]
since `stack ide` is working, could this bug have appeared after https://github.com/lukexi/stack-ide-sublime/pull/4 ?

**Comment by jcpetruzza** [comment]
> since stack ide is working, could this bug have appeared after #4 ?

Could well be. Can you try to set the log verbosity to "normal" and copy what you get in the console?

**Comment by rvion** [comment]
- Verbosity flag doesn't seem to work for `stack ide`.
-  I don't see verbosity level "normal" in the list (only: silent, error, warn, info, debug)

Is there something I do wrong ?

`stack ide --verbosity=silent` gives 

```
{"tag":"ResponseWelcome","contents":[0,1,0]}
{"tag":"ResponseLog","contents":"[Info] Initializing ide-backend session @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:195:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Session dir = /Users/rvion/yesodtest/session.77397 @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:208:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Dist dir = /Users/rvion/yesodtest/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/ @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:210:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Local working dir = /Users/rvion/yesodtest/ @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:217:17)\n"}
{"tag":"ResponseLog","contents":"[Info] Searching for ide-backend-server on this path: /Users/rvion/yesodtest/.stack-work/install/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.stack/snapshots/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.local/bin/:/Users/rvion/.nix-profile/bin:/Users/rvion/.nix-profile/sbin:/Users/rvion/dev/go/bin:/Users/rvion/dev/Nim/bin/:/Users/rvion/.babel/pkgs/babel-0.4.0:/Users/rvion/.babel/bin/:/Users/rvion/Library/Haskell/bin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:341:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Found ide-backend-server - using this one: /Users/rvion/.local/bin/ide-backend-server @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:343:5)\n"}
{"tag":"ResponseLog","contents":"[Debug] Recompile required, starting... @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update.ExecuteSessionUpdate ./IdeSession/Update/ExecuteSessionUpdate.hs:225:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Restarting session due to update requiring it. @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:422:11)\n"}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusRequiredRestart","contents":[]}}
{"tag":"ResponseLog","contents":"[Info] Restarting ide-backend-server @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:351:3)\n"}
{"tag":"ResponseLog","contents":"[Info] Searching for ide-backend-server on this path: /Users/rvion/yesodtest/.stack-work/install/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.stack/snapshots/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.local/bin/:/Users/rvion/.nix-profile/bin:/Users/rvion/.nix-profile/sbin:/Users/rvion/dev/go/bin:/Users/rvion/dev/Nim/bin/:/Users/rvion/.babel/pkgs/babel-0.4.0:/Users/rvion/.babel/bin/:/Users/rvion/Library/Haskell/bin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:341:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Found ide-backend-server - using this one: /Users/rvion/.local/bin/ide-backend-server @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:343:5)\n"}
{"tag":"ResponseLog","contents":"[Debug] Recompile required, starting... @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update.ExecuteSessionUpdate ./IdeSession/Update/ExecuteSessionUpdate.hs:225:5)\n"}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusProgress","contents":{"progressOrigMsg":"[1 of 2] Compiling Paths_yesodtest  ( /Users/rvion/yesodtest/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/Paths_yesodtest.hs, interpreted )","progressStep":1,"progressNumSteps":2,"progressParsedMsg":"Compiling Paths_yesodtest"}}}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusProgress","contents":{"progressOrigMsg":"[2 of 2] Compiling Lib              ( /Users/rvion/yesodtest/src/Lib.hs, interpreted )","progressStep":2,"progressNumSteps":2,"progressParsedMsg":"Compiling Lib"}}}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusDone","contents":[]}}
```

Edit: Oh, OK, I understand: verbosity level of sublime plugin:

it gives me: 

```
startup, version: 3083 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/rvion/Library/Application Support/Sublime Text 3/Packages
state path: /Users/rvion/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/rvion/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage", "SublimeHaskell"]
pre session restore time: 0.212125
using gpu buffer for window
first paint time: 0.278599
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
startup time: 0.445815
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Elm Language Support.Elm Language Support
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "Elm Language Support in /Users/rvion/Library/Application Support/Sublime Text 3/Installed Packages/Elm Language Support.sublime-package", line 330, in <module>
  File "Elm Language Support in /Users/rvion/Library/Application Support/Sublime Text 3/Installed Packages/Elm Language Support.sublime-package", line 77, in load_docs
FileNotFoundError: [Errno 2] No such file or directory: 'docs.json'
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Rails Latest Migration.RailsLatestMigration
reloading plugin stack-ide-sublime.stack-ide
plugins loaded
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bad0>> ignored
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bad0>> ignored
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bad0>> ignored
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bad0>> ignored
Package Control: Skipping automatic upgrade, last run at 2015-07-25 10:17:34, next run at 2015-07-25 11:17:34 or after
Unable to open /Users/rvion/Library/Application Support/Sublime Text 3/Packages/User/SublimeStackIDE.sublime-settings
Unable to open /Users/rvion/Library/Application Support/Sublime Text 3/Packages/SublimeStackIDE/SublimeStackIDE.sublime-settings
reloading Packages/User/SublimeStackIDE.sublime-settings
error: Error trying to parse settings: Expected value in Packages/User/SublimeStackIDE.sublime-settings:2:2
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bc10>> ignored
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bc10>> ignored
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bc10>> ignored
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bc10>> ignored
reloading Packages/User/SublimeStackIDE.sublime-settings
[SublimeStackIDE][NORM]: Resetting StackIDE
[SublimeStackIDE][NORM]: Killing all stack-ide-sublime instances: {2: <stack-ide-sublime.stack-ide.NoStackIDE object at 0x107c6bbd0>, 3: <stack-ide-sublime.stack-ide.NoStackIDE object at 0x107c6bb90>, 4: <stack-ide-sublime.stack-ide.NoStackIDE object at 0x107c6bc90>, 5: <stack-ide-sublime.stack-ide.NoStackIDE object at 0x108114090>}
[SublimeStackIDE][NORM]: Initializing window 2
[SublimeStackIDE][NORM]: Launching stack-ide instance for  /Users/rvion/yesodtest
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bb90>> ignored
[SublimeStackIDE][NORM]: Initializing window 3
[SublimeStackIDE][NORM]: Launching stack-ide instance for  /Users/rvion/yesodtest
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bc90>> ignored
[SublimeStackIDE][NORM]: Initializing window 4
[SublimeStackIDE][NORM]: Launching stack-ide instance for  /Users/rvion/yesodtest
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bb90>> ignored
[SublimeStackIDE][NORM]: Initializing window 5
[SublimeStackIDE][NORM]: Launching stack-ide instance for  /Users/rvion/yesodtest
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bb90>> ignored
[SublimeStackIDE][NORM]: Kicking off window 5
[SublimeStackIDE][NORM]: Kicking off window 5
[SublimeStackIDE][NORM]: Kicking off window 5
[SublimeStackIDE][NORM]: Kicking off window 5
reloading Packages/User/SublimeStackIDE.sublime-settings
[SublimeStackIDE][NORM]: Resetting StackIDE
[SublimeStackIDE][NORM]: Killing all stack-ide-sublime instances: {2: <stack-ide-sublime.stack-ide.NoStackIDE object at 0x107c6bbd0>, 3: <stack-ide-sublime.stack-ide.NoStackIDE object at 0x107c8d250>, 4: <stack-ide-sublime.stack-ide.NoStackIDE object at 0x107c6bc90>, 5: <stack-ide-sublime.stack-ide.NoStackIDE object at 0x108114450>}
[SublimeStackIDE][NORM]: Initializing window 2
[SublimeStackIDE][NORM]: Launching stack-ide instance for  /Users/rvion/yesodtest
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c8d250>> ignored
[SublimeStackIDE][NORM]: Initializing window 3
[SublimeStackIDE][NORM]: Launching stack-ide instance for  /Users/rvion/yesodtest
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c8d250>> ignored
[SublimeStackIDE][NORM]: Initializing window 4
[SublimeStackIDE][NORM]: Launching stack-ide instance for  /Users/rvion/yesodtest
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bc90>> ignored
[SublimeStackIDE][NORM]: Initializing window 5
[SublimeStackIDE][NORM]: Launching stack-ide instance for  /Users/rvion/yesodtest
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x107c6bc90>> ignored
[SublimeStackIDE][NORM]: Kicking off window 5
[SublimeStackIDE][NORM]: Kicking off window 5
[SublimeStackIDE][NORM]: Kicking off window 5
[SublimeStackIDE][NORM]: Kicking off window 5
```

some other notes:

Lots of changes have been made to stack-ide yesterday: https://github.com/commercialhaskell/stack-ide/commits/master
I use the latest version of ST3, without any other packages (just deactived others packages to ensure there is no conflict)

**Comment by rvion** [comment]
some other notes: 
 - Lots of changes have been made to stack-ide yesterday: https://github.com/commercialhaskell/stack-ide/commits/master
 - I use the latest version of ST3, without any other packages (just deactived others packages to ensure there is no conflict)

**Comment by jcpetruzza** [comment]
As a workaround until #6 is merged, try adding `"add_to_PATH": ["foo"]` to your user plugin settings
